local enums = {
    "SDL_INIT_EVERYTHING",
    "SDL_INIT_SENSOR",
    "SDL_INIT_AUDIO",
    "SDL_INIT_VIDEO",
    "SDL_INIT_JOYSTICK",
    "SDL_INIT_GAMECONTROLLER",
    "SDL_INIT_TIMER",
    "SDL_INIT_EVENTS",
    -- Audio
    "AUDIO_S16",
    "AUDIO_S16SYS",
    "AUDIO_F32",
    --* Application events *
    "SDL_QUIT",
    "SDL_APP_TERMINATING",
    "SDL_APP_LOWMEMORY",
    "SDL_APP_WILLENTERBACKGROUND",
    "SDL_APP_DIDENTERBACKGROUND",
    "SDL_APP_WILLENTERFOREGROUND",
    "SDL_APP_DIDENTERFOREGROUND",
    "SDL_LOCALECHANGED",

    -- Display events */
    "SDL_DISPLAYEVENT",

    -- Window events */
    "SDL_WINDOWEVENT",

    -- Keyboard events */
    "SDL_KEYDOWN",
    "SDL_KEYUP",
    "SDL_TEXTEDITING",
    "SDL_TEXTINPUT",
    "SDL_KEYMAPCHANGED",
    "SDL_TEXTEDITING_EXT",

    -- Mouse events */
    "SDL_MOUSEMOTION",
    "SDL_MOUSEBUTTONDOWN",
    "SDL_MOUSEBUTTONUP",
    "SDL_MOUSEWHEEL",

    -- Joystick events */
    "SDL_JOYAXISMOTION",
    "SDL_JOYBALLMOTION",
    "SDL_JOYHATMOTION",
    "SDL_JOYBUTTONDOWN",
    "SDL_JOYBUTTONUP",
    "SDL_JOYDEVICEADDED",
    "SDL_JOYDEVICEREMOVED",
    "SDL_JOYBATTERYUPDATED",

    -- Game controller events */
    "SDL_CONTROLLERAXISMOTION",
    "SDL_CONTROLLERBUTTONDOWN",
    "SDL_CONTROLLERBUTTONUP",
    "SDL_CONTROLLERDEVICEADDED",
    "SDL_CONTROLLERDEVICEREMOVED",
    "SDL_CONTROLLERDEVICEREMAPPED",
    "SDL_CONTROLLERTOUCHPADDOWN",
    "SDL_CONTROLLERTOUCHPADMOTION",
    "SDL_CONTROLLERTOUCHPADUP",
    "SDL_CONTROLLERSENSORUPDATE",

    -- Touch events */
    "SDL_FINGERDOWN",
    "SDL_FINGERUP",
    "SDL_FINGERMOTION",

    -- Gesture events */
    "SDL_DOLLARGESTURE",
    "SDL_DOLLARRECORD",
    "SDL_MULTIGESTURE",

    -- Clipboard events */
    "SDL_CLIPBOARDUPDATE",

    -- Drag and drop events */
    "SDL_DROPFILE",
    "SDL_DROPTEXT",
    "SDL_DROPBEGIN",
    "SDL_DROPCOMPLETE",

    -- Audio hotplug events */
    "SDL_AUDIODEVICEADDED",
    "SDL_AUDIODEVICEREMOVED",

    -- Sensor events */
    "SDL_SENSORUPDATE",

    -- Render events */
    "SDL_RENDER_TARGETS_RESET",
    "SDL_RENDER_DEVICE_RESET",

    -- Renderer
    "SDL_RENDERER_ACCELERATED",
    "SDL_RENDERER_TARGETTEXTURE",

    -- Window Events
    "SDL_WINDOWEVENT_CLOSE",
    "SDL_WINDOWEVENT_SIZE_CHANGED",
    "SDL_WINDOWEVENT_RESIZED",
    "SDL_WINDOWEVENT_MOVED",
    "SDL_WINDOWEVENT_MINIMIZED",
    "SDL_WINDOWEVENT_MAXIMIZED",
    "SDL_WINDOWEVENT_RESTORED",
    "SDL_WINDOWEVENT_SHOWN",
    "SDL_WINDOWEVENT_HIDDEN",
    "SDL_WINDOWEVENT_ENTER",
    "SDL_WINDOWEVENT_LEAVE",
    "SDL_WINDOWEVENT_FOCUS_GAINED",
    "SDL_WINDOWEVENT_FOCUS_LOST",
    "SDL_WINDOWEVENT_TAKE_FOCUS",
    "SDL_WINDOWEVENT_HIT_TEST",

    -- Window Flags
    "SDL_WINDOW_SHOWN",
    "SDL_WINDOW_OPENGL",
    "SDL_WINDOW_RESIZABLE",
    "SDL_WINDOW_FULLSCREEN",
    "SDL_WINDOW_FULLSCREEN_DESKTOP",
    "SDL_WINDOW_BORDERLESS",
    "SDL_WINDOW_ALWAYS_ON_TOP",

    "SDL_WINDOWPOS_CENTERED",
    -- Message Box
    "SDL_MESSAGEBOX_ERROR",
    "SDL_MESSAGEBOX_WARNING",
    "SDL_MESSAGEBOX_INFORMATION",
    -- GL
    "SDL_GL_DOUBLEBUFFER",
    "SDL_GL_DEPTH_SIZE",
    "SDL_GL_STENCIL_SIZE",
    "SDL_GL_CONTEXT_PROFILE_MASK",
    "SDL_GL_CONTEXT_MAJOR_VERSION",
    "SDL_GL_CONTEXT_MINOR_VERSION",
    "SDL_GL_CONTEXT_PROFILE_CORE",
    "SDL_GL_CONTEXT_PROFILE_COMPATIBILITY",
    "SDL_GL_CONTEXT_PROFILE_ES",
    -- TextureAccess
    "SDL_TEXTUREACCESS_STATIC",
    "SDL_TEXTUREACCESS_STREAMING",
    "SDL_TEXTUREACCESS_TARGET",

    -- PixelFormat
    "SDL_PIXELFORMAT_UNKNOWN",
    "SDL_PIXELFORMAT_RGB332",
    "SDL_PIXELFORMAT_RGB444",
    "SDL_PIXELFORMAT_RGB555",
    "SDL_PIXELFORMAT_BGR555",
    "SDL_PIXELFORMAT_ARGB4444",
    "SDL_PIXELFORMAT_RGBA4444",
    "SDL_PIXELFORMAT_ABGR4444",
    "SDL_PIXELFORMAT_BGRA4444",
    "SDL_PIXELFORMAT_RGB565",
    "SDL_PIXELFORMAT_BGR565",
    "SDL_PIXELFORMAT_RGB24",
    "SDL_PIXELFORMAT_BGR24",
    "SDL_PIXELFORMAT_RGB888",
    "SDL_PIXELFORMAT_BGR888",
    "SDL_PIXELFORMAT_ARGB8888",
    "SDL_PIXELFORMAT_RGBA8888",
    "SDL_PIXELFORMAT_ABGR8888",
    "SDL_PIXELFORMAT_BGRA8888",
    "SDL_PIXELFORMAT_RGBA32",
    "SDL_PIXELFORMAT_ARGB32",
    "SDL_PIXELFORMAT_BGRA32",
    "SDL_PIXELFORMAT_ABGR32",

    -- BlendMode
    "SDL_BLENDMODE_NONE",
    "SDL_BLENDMODE_BLEND",
    "SDL_BLENDMODE_ADD",
    "SDL_BLENDMODE_MOD",
    "SDL_BLENDMODE_MUL",
    "SDL_BLENDMODE_INVALID",

    -- RenderFlip
    "SDL_FLIP_NONE",
    "SDL_FLIP_VERTICAL",
    "SDL_FLIP_HORIZONTAL",

    -- ScaleMode
    "SDL_ScaleModeNearest",
    "SDL_ScaleModeLinear",
    "SDL_ScaleModeBest",
}
return enums