message("Check For SDL2 lib")

if (DEFINED MSVC)
    set(SDL2_DIR src/third/SDL2/MSVC/cmake)
elseif (DEFINED MINGW)
    set(SDL2_DIR src/third/SDL2/MINGW/cmake)
endif ()

if (DEFINED SDL2_DIR)
    find_package(SDL2 REQUIRED)
else ()
    find_library(SDL2_Lib NAMES SDL2)
    if (NOT SDL2_Lib)
        find_library(SDL2_Lib NAMES SDL2 PATHS "${CMAKE_SOURCE_DIR}/dist/${triple}${LIB_PLATFORM}")
    endif ()
    find_library(SDL2_Main_Lib NAMES SDL2main PATHS "${CMAKE_SOURCE_DIR}/dist/${triple}${LIB_PLATFORM}")
    find_path(SDL2_INCLUDE_DIR NAMES SDL2/SDL.h)
    if (NOT SDL2_INCLUDE_DIR)
        message ("Not found")
        find_path(SDL2_INCLUDE_DIR NAMES SDL2/SDL.h PATHS "${CMAKE_SOURCE_DIR}/src/third/SDL2/SDL/include")
    endif ()
    set (SDL2_INCLUDE_DIRS ${SDL2_INCLUDE_DIR}/SDL2)
endif ()

message("SDL2 Library ${SDL2_Lib}")
message("SDL2 INCLUDE ${SDL2_INCLUDE_DIRS}")

if ((NOT SDL2_FOUND AND SDL2_Lib) AND NOT TARGET SDL2::SDL2)
    message ("Import SDL2 Library")
    add_library(SDL2::SDL2 SHARED IMPORTED)
    set_property(TARGET SDL2::SDL2 PROPERTY IMPORTED_LOCATION ${SDL2_Lib})
    set (SDL2_LIBRARIES SDL2::SDL2)
    if (SDL2_Main_Lib AND NOT TARGET SDL2::Main)
        add_library(SDL2::Main SHARED IMPORTED)
        set_property(TARGET SDL2::Main PROPERTY IMPORTED_LOCATION ${SDL2_Main_Lib})
        target_link_libraries(SDL2::Main INTERFACE SDL2::SDL2)
        set (SDL2_LIBRARIES ${SDL2_LIBRARIES} SDL2::Main)
    endif ()
elseif (NOT SDL2_Lib AND NOT SDL2_FOUND)
    add_subdirectory(src/third/SDL2/source)
endif ()

