# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/canoi/Documentos/selene

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/canoi/Documentos/selene

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/canoi/Documentos/selene/CMakeFiles /home/canoi/Documentos/selene//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/canoi/Documentos/selene/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named lua

# Build rule for target.
lua: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lua
.PHONY : lua

# fast build rule for target.
lua/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/build
.PHONY : lua/fast

#=============================================================================
# Target rules for targets named selene

# Build rule for target.
selene: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 selene
.PHONY : selene

# fast build rule for target.
selene/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/selene.dir/build.make CMakeFiles/selene.dir/build
.PHONY : selene/fast

external/glad/src/glad.o: external/glad/src/glad.c.o
.PHONY : external/glad/src/glad.o

# target to build an object file
external/glad/src/glad.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/selene.dir/build.make CMakeFiles/selene.dir/external/glad/src/glad.c.o
.PHONY : external/glad/src/glad.c.o

external/glad/src/glad.i: external/glad/src/glad.c.i
.PHONY : external/glad/src/glad.i

# target to preprocess a source file
external/glad/src/glad.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/selene.dir/build.make CMakeFiles/selene.dir/external/glad/src/glad.c.i
.PHONY : external/glad/src/glad.c.i

external/glad/src/glad.s: external/glad/src/glad.c.s
.PHONY : external/glad/src/glad.s

# target to generate assembly for a file
external/glad/src/glad.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/selene.dir/build.make CMakeFiles/selene.dir/external/glad/src/glad.c.s
.PHONY : external/glad/src/glad.c.s

external/lua/src/lapi.o: external/lua/src/lapi.c.o
.PHONY : external/lua/src/lapi.o

# target to build an object file
external/lua/src/lapi.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/external/lua/src/lapi.c.o
.PHONY : external/lua/src/lapi.c.o

external/lua/src/lapi.i: external/lua/src/lapi.c.i
.PHONY : external/lua/src/lapi.i

# target to preprocess a source file
external/lua/src/lapi.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/external/lua/src/lapi.c.i
.PHONY : external/lua/src/lapi.c.i

external/lua/src/lapi.s: external/lua/src/lapi.c.s
.PHONY : external/lua/src/lapi.s

# target to generate assembly for a file
external/lua/src/lapi.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/external/lua/src/lapi.c.s
.PHONY : external/lua/src/lapi.c.s

external/lua/src/lauxlib.o: external/lua/src/lauxlib.c.o
.PHONY : external/lua/src/lauxlib.o

# target to build an object file
external/lua/src/lauxlib.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/external/lua/src/lauxlib.c.o
.PHONY : external/lua/src/lauxlib.c.o

external/lua/src/lauxlib.i: external/lua/src/lauxlib.c.i
.PHONY : external/lua/src/lauxlib.i

# target to preprocess a source file
external/lua/src/lauxlib.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/external/lua/src/lauxlib.c.i
.PHONY : external/lua/src/lauxlib.c.i

external/lua/src/lauxlib.s: external/lua/src/lauxlib.c.s
.PHONY : external/lua/src/lauxlib.s

# target to generate assembly for a file
external/lua/src/lauxlib.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/external/lua/src/lauxlib.c.s
.PHONY : external/lua/src/lauxlib.c.s

external/lua/src/lbaselib.o: external/lua/src/lbaselib.c.o
.PHONY : external/lua/src/lbaselib.o

# target to build an object file
external/lua/src/lbaselib.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/external/lua/src/lbaselib.c.o
.PHONY : external/lua/src/lbaselib.c.o

external/lua/src/lbaselib.i: external/lua/src/lbaselib.c.i
.PHONY : external/lua/src/lbaselib.i

# target to preprocess a source file
external/lua/src/lbaselib.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/external/lua/src/lbaselib.c.i
.PHONY : external/lua/src/lbaselib.c.i

external/lua/src/lbaselib.s: external/lua/src/lbaselib.c.s
.PHONY : external/lua/src/lbaselib.s

# target to generate assembly for a file
external/lua/src/lbaselib.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/external/lua/src/lbaselib.c.s
.PHONY : external/lua/src/lbaselib.c.s

external/lua/src/lcode.o: external/lua/src/lcode.c.o
.PHONY : external/lua/src/lcode.o

# target to build an object file
external/lua/src/lcode.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/external/lua/src/lcode.c.o
.PHONY : external/lua/src/lcode.c.o

external/lua/src/lcode.i: external/lua/src/lcode.c.i
.PHONY : external/lua/src/lcode.i

# target to preprocess a source file
external/lua/src/lcode.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/external/lua/src/lcode.c.i
.PHONY : external/lua/src/lcode.c.i

external/lua/src/lcode.s: external/lua/src/lcode.c.s
.PHONY : external/lua/src/lcode.s

# target to generate assembly for a file
external/lua/src/lcode.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/external/lua/src/lcode.c.s
.PHONY : external/lua/src/lcode.c.s

external/lua/src/lcorolib.o: external/lua/src/lcorolib.c.o
.PHONY : external/lua/src/lcorolib.o

# target to build an object file
external/lua/src/lcorolib.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/external/lua/src/lcorolib.c.o
.PHONY : external/lua/src/lcorolib.c.o

external/lua/src/lcorolib.i: external/lua/src/lcorolib.c.i
.PHONY : external/lua/src/lcorolib.i

# target to preprocess a source file
external/lua/src/lcorolib.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/external/lua/src/lcorolib.c.i
.PHONY : external/lua/src/lcorolib.c.i

external/lua/src/lcorolib.s: external/lua/src/lcorolib.c.s
.PHONY : external/lua/src/lcorolib.s

# target to generate assembly for a file
external/lua/src/lcorolib.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/external/lua/src/lcorolib.c.s
.PHONY : external/lua/src/lcorolib.c.s

external/lua/src/lctype.o: external/lua/src/lctype.c.o
.PHONY : external/lua/src/lctype.o

# target to build an object file
external/lua/src/lctype.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/external/lua/src/lctype.c.o
.PHONY : external/lua/src/lctype.c.o

external/lua/src/lctype.i: external/lua/src/lctype.c.i
.PHONY : external/lua/src/lctype.i

# target to preprocess a source file
external/lua/src/lctype.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/external/lua/src/lctype.c.i
.PHONY : external/lua/src/lctype.c.i

external/lua/src/lctype.s: external/lua/src/lctype.c.s
.PHONY : external/lua/src/lctype.s

# target to generate assembly for a file
external/lua/src/lctype.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/external/lua/src/lctype.c.s
.PHONY : external/lua/src/lctype.c.s

external/lua/src/ldblib.o: external/lua/src/ldblib.c.o
.PHONY : external/lua/src/ldblib.o

# target to build an object file
external/lua/src/ldblib.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/external/lua/src/ldblib.c.o
.PHONY : external/lua/src/ldblib.c.o

external/lua/src/ldblib.i: external/lua/src/ldblib.c.i
.PHONY : external/lua/src/ldblib.i

# target to preprocess a source file
external/lua/src/ldblib.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/external/lua/src/ldblib.c.i
.PHONY : external/lua/src/ldblib.c.i

external/lua/src/ldblib.s: external/lua/src/ldblib.c.s
.PHONY : external/lua/src/ldblib.s

# target to generate assembly for a file
external/lua/src/ldblib.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/external/lua/src/ldblib.c.s
.PHONY : external/lua/src/ldblib.c.s

external/lua/src/ldebug.o: external/lua/src/ldebug.c.o
.PHONY : external/lua/src/ldebug.o

# target to build an object file
external/lua/src/ldebug.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/external/lua/src/ldebug.c.o
.PHONY : external/lua/src/ldebug.c.o

external/lua/src/ldebug.i: external/lua/src/ldebug.c.i
.PHONY : external/lua/src/ldebug.i

# target to preprocess a source file
external/lua/src/ldebug.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/external/lua/src/ldebug.c.i
.PHONY : external/lua/src/ldebug.c.i

external/lua/src/ldebug.s: external/lua/src/ldebug.c.s
.PHONY : external/lua/src/ldebug.s

# target to generate assembly for a file
external/lua/src/ldebug.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/external/lua/src/ldebug.c.s
.PHONY : external/lua/src/ldebug.c.s

external/lua/src/ldo.o: external/lua/src/ldo.c.o
.PHONY : external/lua/src/ldo.o

# target to build an object file
external/lua/src/ldo.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/external/lua/src/ldo.c.o
.PHONY : external/lua/src/ldo.c.o

external/lua/src/ldo.i: external/lua/src/ldo.c.i
.PHONY : external/lua/src/ldo.i

# target to preprocess a source file
external/lua/src/ldo.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/external/lua/src/ldo.c.i
.PHONY : external/lua/src/ldo.c.i

external/lua/src/ldo.s: external/lua/src/ldo.c.s
.PHONY : external/lua/src/ldo.s

# target to generate assembly for a file
external/lua/src/ldo.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/external/lua/src/ldo.c.s
.PHONY : external/lua/src/ldo.c.s

external/lua/src/ldump.o: external/lua/src/ldump.c.o
.PHONY : external/lua/src/ldump.o

# target to build an object file
external/lua/src/ldump.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/external/lua/src/ldump.c.o
.PHONY : external/lua/src/ldump.c.o

external/lua/src/ldump.i: external/lua/src/ldump.c.i
.PHONY : external/lua/src/ldump.i

# target to preprocess a source file
external/lua/src/ldump.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/external/lua/src/ldump.c.i
.PHONY : external/lua/src/ldump.c.i

external/lua/src/ldump.s: external/lua/src/ldump.c.s
.PHONY : external/lua/src/ldump.s

# target to generate assembly for a file
external/lua/src/ldump.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/external/lua/src/ldump.c.s
.PHONY : external/lua/src/ldump.c.s

external/lua/src/lfunc.o: external/lua/src/lfunc.c.o
.PHONY : external/lua/src/lfunc.o

# target to build an object file
external/lua/src/lfunc.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/external/lua/src/lfunc.c.o
.PHONY : external/lua/src/lfunc.c.o

external/lua/src/lfunc.i: external/lua/src/lfunc.c.i
.PHONY : external/lua/src/lfunc.i

# target to preprocess a source file
external/lua/src/lfunc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/external/lua/src/lfunc.c.i
.PHONY : external/lua/src/lfunc.c.i

external/lua/src/lfunc.s: external/lua/src/lfunc.c.s
.PHONY : external/lua/src/lfunc.s

# target to generate assembly for a file
external/lua/src/lfunc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/external/lua/src/lfunc.c.s
.PHONY : external/lua/src/lfunc.c.s

external/lua/src/lgc.o: external/lua/src/lgc.c.o
.PHONY : external/lua/src/lgc.o

# target to build an object file
external/lua/src/lgc.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/external/lua/src/lgc.c.o
.PHONY : external/lua/src/lgc.c.o

external/lua/src/lgc.i: external/lua/src/lgc.c.i
.PHONY : external/lua/src/lgc.i

# target to preprocess a source file
external/lua/src/lgc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/external/lua/src/lgc.c.i
.PHONY : external/lua/src/lgc.c.i

external/lua/src/lgc.s: external/lua/src/lgc.c.s
.PHONY : external/lua/src/lgc.s

# target to generate assembly for a file
external/lua/src/lgc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/external/lua/src/lgc.c.s
.PHONY : external/lua/src/lgc.c.s

external/lua/src/linit.o: external/lua/src/linit.c.o
.PHONY : external/lua/src/linit.o

# target to build an object file
external/lua/src/linit.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/external/lua/src/linit.c.o
.PHONY : external/lua/src/linit.c.o

external/lua/src/linit.i: external/lua/src/linit.c.i
.PHONY : external/lua/src/linit.i

# target to preprocess a source file
external/lua/src/linit.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/external/lua/src/linit.c.i
.PHONY : external/lua/src/linit.c.i

external/lua/src/linit.s: external/lua/src/linit.c.s
.PHONY : external/lua/src/linit.s

# target to generate assembly for a file
external/lua/src/linit.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/external/lua/src/linit.c.s
.PHONY : external/lua/src/linit.c.s

external/lua/src/liolib.o: external/lua/src/liolib.c.o
.PHONY : external/lua/src/liolib.o

# target to build an object file
external/lua/src/liolib.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/external/lua/src/liolib.c.o
.PHONY : external/lua/src/liolib.c.o

external/lua/src/liolib.i: external/lua/src/liolib.c.i
.PHONY : external/lua/src/liolib.i

# target to preprocess a source file
external/lua/src/liolib.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/external/lua/src/liolib.c.i
.PHONY : external/lua/src/liolib.c.i

external/lua/src/liolib.s: external/lua/src/liolib.c.s
.PHONY : external/lua/src/liolib.s

# target to generate assembly for a file
external/lua/src/liolib.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/external/lua/src/liolib.c.s
.PHONY : external/lua/src/liolib.c.s

external/lua/src/llex.o: external/lua/src/llex.c.o
.PHONY : external/lua/src/llex.o

# target to build an object file
external/lua/src/llex.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/external/lua/src/llex.c.o
.PHONY : external/lua/src/llex.c.o

external/lua/src/llex.i: external/lua/src/llex.c.i
.PHONY : external/lua/src/llex.i

# target to preprocess a source file
external/lua/src/llex.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/external/lua/src/llex.c.i
.PHONY : external/lua/src/llex.c.i

external/lua/src/llex.s: external/lua/src/llex.c.s
.PHONY : external/lua/src/llex.s

# target to generate assembly for a file
external/lua/src/llex.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/external/lua/src/llex.c.s
.PHONY : external/lua/src/llex.c.s

external/lua/src/lmathlib.o: external/lua/src/lmathlib.c.o
.PHONY : external/lua/src/lmathlib.o

# target to build an object file
external/lua/src/lmathlib.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/external/lua/src/lmathlib.c.o
.PHONY : external/lua/src/lmathlib.c.o

external/lua/src/lmathlib.i: external/lua/src/lmathlib.c.i
.PHONY : external/lua/src/lmathlib.i

# target to preprocess a source file
external/lua/src/lmathlib.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/external/lua/src/lmathlib.c.i
.PHONY : external/lua/src/lmathlib.c.i

external/lua/src/lmathlib.s: external/lua/src/lmathlib.c.s
.PHONY : external/lua/src/lmathlib.s

# target to generate assembly for a file
external/lua/src/lmathlib.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/external/lua/src/lmathlib.c.s
.PHONY : external/lua/src/lmathlib.c.s

external/lua/src/lmem.o: external/lua/src/lmem.c.o
.PHONY : external/lua/src/lmem.o

# target to build an object file
external/lua/src/lmem.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/external/lua/src/lmem.c.o
.PHONY : external/lua/src/lmem.c.o

external/lua/src/lmem.i: external/lua/src/lmem.c.i
.PHONY : external/lua/src/lmem.i

# target to preprocess a source file
external/lua/src/lmem.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/external/lua/src/lmem.c.i
.PHONY : external/lua/src/lmem.c.i

external/lua/src/lmem.s: external/lua/src/lmem.c.s
.PHONY : external/lua/src/lmem.s

# target to generate assembly for a file
external/lua/src/lmem.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/external/lua/src/lmem.c.s
.PHONY : external/lua/src/lmem.c.s

external/lua/src/loadlib.o: external/lua/src/loadlib.c.o
.PHONY : external/lua/src/loadlib.o

# target to build an object file
external/lua/src/loadlib.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/external/lua/src/loadlib.c.o
.PHONY : external/lua/src/loadlib.c.o

external/lua/src/loadlib.i: external/lua/src/loadlib.c.i
.PHONY : external/lua/src/loadlib.i

# target to preprocess a source file
external/lua/src/loadlib.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/external/lua/src/loadlib.c.i
.PHONY : external/lua/src/loadlib.c.i

external/lua/src/loadlib.s: external/lua/src/loadlib.c.s
.PHONY : external/lua/src/loadlib.s

# target to generate assembly for a file
external/lua/src/loadlib.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/external/lua/src/loadlib.c.s
.PHONY : external/lua/src/loadlib.c.s

external/lua/src/lobject.o: external/lua/src/lobject.c.o
.PHONY : external/lua/src/lobject.o

# target to build an object file
external/lua/src/lobject.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/external/lua/src/lobject.c.o
.PHONY : external/lua/src/lobject.c.o

external/lua/src/lobject.i: external/lua/src/lobject.c.i
.PHONY : external/lua/src/lobject.i

# target to preprocess a source file
external/lua/src/lobject.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/external/lua/src/lobject.c.i
.PHONY : external/lua/src/lobject.c.i

external/lua/src/lobject.s: external/lua/src/lobject.c.s
.PHONY : external/lua/src/lobject.s

# target to generate assembly for a file
external/lua/src/lobject.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/external/lua/src/lobject.c.s
.PHONY : external/lua/src/lobject.c.s

external/lua/src/lopcodes.o: external/lua/src/lopcodes.c.o
.PHONY : external/lua/src/lopcodes.o

# target to build an object file
external/lua/src/lopcodes.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/external/lua/src/lopcodes.c.o
.PHONY : external/lua/src/lopcodes.c.o

external/lua/src/lopcodes.i: external/lua/src/lopcodes.c.i
.PHONY : external/lua/src/lopcodes.i

# target to preprocess a source file
external/lua/src/lopcodes.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/external/lua/src/lopcodes.c.i
.PHONY : external/lua/src/lopcodes.c.i

external/lua/src/lopcodes.s: external/lua/src/lopcodes.c.s
.PHONY : external/lua/src/lopcodes.s

# target to generate assembly for a file
external/lua/src/lopcodes.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/external/lua/src/lopcodes.c.s
.PHONY : external/lua/src/lopcodes.c.s

external/lua/src/loslib.o: external/lua/src/loslib.c.o
.PHONY : external/lua/src/loslib.o

# target to build an object file
external/lua/src/loslib.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/external/lua/src/loslib.c.o
.PHONY : external/lua/src/loslib.c.o

external/lua/src/loslib.i: external/lua/src/loslib.c.i
.PHONY : external/lua/src/loslib.i

# target to preprocess a source file
external/lua/src/loslib.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/external/lua/src/loslib.c.i
.PHONY : external/lua/src/loslib.c.i

external/lua/src/loslib.s: external/lua/src/loslib.c.s
.PHONY : external/lua/src/loslib.s

# target to generate assembly for a file
external/lua/src/loslib.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/external/lua/src/loslib.c.s
.PHONY : external/lua/src/loslib.c.s

external/lua/src/lparser.o: external/lua/src/lparser.c.o
.PHONY : external/lua/src/lparser.o

# target to build an object file
external/lua/src/lparser.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/external/lua/src/lparser.c.o
.PHONY : external/lua/src/lparser.c.o

external/lua/src/lparser.i: external/lua/src/lparser.c.i
.PHONY : external/lua/src/lparser.i

# target to preprocess a source file
external/lua/src/lparser.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/external/lua/src/lparser.c.i
.PHONY : external/lua/src/lparser.c.i

external/lua/src/lparser.s: external/lua/src/lparser.c.s
.PHONY : external/lua/src/lparser.s

# target to generate assembly for a file
external/lua/src/lparser.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/external/lua/src/lparser.c.s
.PHONY : external/lua/src/lparser.c.s

external/lua/src/lstate.o: external/lua/src/lstate.c.o
.PHONY : external/lua/src/lstate.o

# target to build an object file
external/lua/src/lstate.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/external/lua/src/lstate.c.o
.PHONY : external/lua/src/lstate.c.o

external/lua/src/lstate.i: external/lua/src/lstate.c.i
.PHONY : external/lua/src/lstate.i

# target to preprocess a source file
external/lua/src/lstate.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/external/lua/src/lstate.c.i
.PHONY : external/lua/src/lstate.c.i

external/lua/src/lstate.s: external/lua/src/lstate.c.s
.PHONY : external/lua/src/lstate.s

# target to generate assembly for a file
external/lua/src/lstate.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/external/lua/src/lstate.c.s
.PHONY : external/lua/src/lstate.c.s

external/lua/src/lstring.o: external/lua/src/lstring.c.o
.PHONY : external/lua/src/lstring.o

# target to build an object file
external/lua/src/lstring.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/external/lua/src/lstring.c.o
.PHONY : external/lua/src/lstring.c.o

external/lua/src/lstring.i: external/lua/src/lstring.c.i
.PHONY : external/lua/src/lstring.i

# target to preprocess a source file
external/lua/src/lstring.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/external/lua/src/lstring.c.i
.PHONY : external/lua/src/lstring.c.i

external/lua/src/lstring.s: external/lua/src/lstring.c.s
.PHONY : external/lua/src/lstring.s

# target to generate assembly for a file
external/lua/src/lstring.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/external/lua/src/lstring.c.s
.PHONY : external/lua/src/lstring.c.s

external/lua/src/lstrlib.o: external/lua/src/lstrlib.c.o
.PHONY : external/lua/src/lstrlib.o

# target to build an object file
external/lua/src/lstrlib.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/external/lua/src/lstrlib.c.o
.PHONY : external/lua/src/lstrlib.c.o

external/lua/src/lstrlib.i: external/lua/src/lstrlib.c.i
.PHONY : external/lua/src/lstrlib.i

# target to preprocess a source file
external/lua/src/lstrlib.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/external/lua/src/lstrlib.c.i
.PHONY : external/lua/src/lstrlib.c.i

external/lua/src/lstrlib.s: external/lua/src/lstrlib.c.s
.PHONY : external/lua/src/lstrlib.s

# target to generate assembly for a file
external/lua/src/lstrlib.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/external/lua/src/lstrlib.c.s
.PHONY : external/lua/src/lstrlib.c.s

external/lua/src/ltable.o: external/lua/src/ltable.c.o
.PHONY : external/lua/src/ltable.o

# target to build an object file
external/lua/src/ltable.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/external/lua/src/ltable.c.o
.PHONY : external/lua/src/ltable.c.o

external/lua/src/ltable.i: external/lua/src/ltable.c.i
.PHONY : external/lua/src/ltable.i

# target to preprocess a source file
external/lua/src/ltable.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/external/lua/src/ltable.c.i
.PHONY : external/lua/src/ltable.c.i

external/lua/src/ltable.s: external/lua/src/ltable.c.s
.PHONY : external/lua/src/ltable.s

# target to generate assembly for a file
external/lua/src/ltable.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/external/lua/src/ltable.c.s
.PHONY : external/lua/src/ltable.c.s

external/lua/src/ltablib.o: external/lua/src/ltablib.c.o
.PHONY : external/lua/src/ltablib.o

# target to build an object file
external/lua/src/ltablib.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/external/lua/src/ltablib.c.o
.PHONY : external/lua/src/ltablib.c.o

external/lua/src/ltablib.i: external/lua/src/ltablib.c.i
.PHONY : external/lua/src/ltablib.i

# target to preprocess a source file
external/lua/src/ltablib.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/external/lua/src/ltablib.c.i
.PHONY : external/lua/src/ltablib.c.i

external/lua/src/ltablib.s: external/lua/src/ltablib.c.s
.PHONY : external/lua/src/ltablib.s

# target to generate assembly for a file
external/lua/src/ltablib.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/external/lua/src/ltablib.c.s
.PHONY : external/lua/src/ltablib.c.s

external/lua/src/ltm.o: external/lua/src/ltm.c.o
.PHONY : external/lua/src/ltm.o

# target to build an object file
external/lua/src/ltm.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/external/lua/src/ltm.c.o
.PHONY : external/lua/src/ltm.c.o

external/lua/src/ltm.i: external/lua/src/ltm.c.i
.PHONY : external/lua/src/ltm.i

# target to preprocess a source file
external/lua/src/ltm.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/external/lua/src/ltm.c.i
.PHONY : external/lua/src/ltm.c.i

external/lua/src/ltm.s: external/lua/src/ltm.c.s
.PHONY : external/lua/src/ltm.s

# target to generate assembly for a file
external/lua/src/ltm.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/external/lua/src/ltm.c.s
.PHONY : external/lua/src/ltm.c.s

external/lua/src/lua.o: external/lua/src/lua.c.o
.PHONY : external/lua/src/lua.o

# target to build an object file
external/lua/src/lua.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/external/lua/src/lua.c.o
.PHONY : external/lua/src/lua.c.o

external/lua/src/lua.i: external/lua/src/lua.c.i
.PHONY : external/lua/src/lua.i

# target to preprocess a source file
external/lua/src/lua.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/external/lua/src/lua.c.i
.PHONY : external/lua/src/lua.c.i

external/lua/src/lua.s: external/lua/src/lua.c.s
.PHONY : external/lua/src/lua.s

# target to generate assembly for a file
external/lua/src/lua.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/external/lua/src/lua.c.s
.PHONY : external/lua/src/lua.c.s

external/lua/src/luac.o: external/lua/src/luac.c.o
.PHONY : external/lua/src/luac.o

# target to build an object file
external/lua/src/luac.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/external/lua/src/luac.c.o
.PHONY : external/lua/src/luac.c.o

external/lua/src/luac.i: external/lua/src/luac.c.i
.PHONY : external/lua/src/luac.i

# target to preprocess a source file
external/lua/src/luac.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/external/lua/src/luac.c.i
.PHONY : external/lua/src/luac.c.i

external/lua/src/luac.s: external/lua/src/luac.c.s
.PHONY : external/lua/src/luac.s

# target to generate assembly for a file
external/lua/src/luac.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/external/lua/src/luac.c.s
.PHONY : external/lua/src/luac.c.s

external/lua/src/lundump.o: external/lua/src/lundump.c.o
.PHONY : external/lua/src/lundump.o

# target to build an object file
external/lua/src/lundump.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/external/lua/src/lundump.c.o
.PHONY : external/lua/src/lundump.c.o

external/lua/src/lundump.i: external/lua/src/lundump.c.i
.PHONY : external/lua/src/lundump.i

# target to preprocess a source file
external/lua/src/lundump.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/external/lua/src/lundump.c.i
.PHONY : external/lua/src/lundump.c.i

external/lua/src/lundump.s: external/lua/src/lundump.c.s
.PHONY : external/lua/src/lundump.s

# target to generate assembly for a file
external/lua/src/lundump.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/external/lua/src/lundump.c.s
.PHONY : external/lua/src/lundump.c.s

external/lua/src/lutf8lib.o: external/lua/src/lutf8lib.c.o
.PHONY : external/lua/src/lutf8lib.o

# target to build an object file
external/lua/src/lutf8lib.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/external/lua/src/lutf8lib.c.o
.PHONY : external/lua/src/lutf8lib.c.o

external/lua/src/lutf8lib.i: external/lua/src/lutf8lib.c.i
.PHONY : external/lua/src/lutf8lib.i

# target to preprocess a source file
external/lua/src/lutf8lib.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/external/lua/src/lutf8lib.c.i
.PHONY : external/lua/src/lutf8lib.c.i

external/lua/src/lutf8lib.s: external/lua/src/lutf8lib.c.s
.PHONY : external/lua/src/lutf8lib.s

# target to generate assembly for a file
external/lua/src/lutf8lib.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/external/lua/src/lutf8lib.c.s
.PHONY : external/lua/src/lutf8lib.c.s

external/lua/src/lvm.o: external/lua/src/lvm.c.o
.PHONY : external/lua/src/lvm.o

# target to build an object file
external/lua/src/lvm.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/external/lua/src/lvm.c.o
.PHONY : external/lua/src/lvm.c.o

external/lua/src/lvm.i: external/lua/src/lvm.c.i
.PHONY : external/lua/src/lvm.i

# target to preprocess a source file
external/lua/src/lvm.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/external/lua/src/lvm.c.i
.PHONY : external/lua/src/lvm.c.i

external/lua/src/lvm.s: external/lua/src/lvm.c.s
.PHONY : external/lua/src/lvm.s

# target to generate assembly for a file
external/lua/src/lvm.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/external/lua/src/lvm.c.s
.PHONY : external/lua/src/lvm.c.s

external/lua/src/lzio.o: external/lua/src/lzio.c.o
.PHONY : external/lua/src/lzio.o

# target to build an object file
external/lua/src/lzio.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/external/lua/src/lzio.c.o
.PHONY : external/lua/src/lzio.c.o

external/lua/src/lzio.i: external/lua/src/lzio.c.i
.PHONY : external/lua/src/lzio.i

# target to preprocess a source file
external/lua/src/lzio.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/external/lua/src/lzio.c.i
.PHONY : external/lua/src/lzio.c.i

external/lua/src/lzio.s: external/lua/src/lzio.c.s
.PHONY : external/lua/src/lzio.s

# target to generate assembly for a file
external/lua/src/lzio.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/external/lua/src/lzio.c.s
.PHONY : external/lua/src/lzio.c.s

selene.o: selene.c.o
.PHONY : selene.o

# target to build an object file
selene.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/selene.dir/build.make CMakeFiles/selene.dir/selene.c.o
.PHONY : selene.c.o

selene.i: selene.c.i
.PHONY : selene.i

# target to preprocess a source file
selene.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/selene.dir/build.make CMakeFiles/selene.dir/selene.c.i
.PHONY : selene.c.i

selene.s: selene.c.s
.PHONY : selene.s

# target to generate assembly for a file
selene.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/selene.dir/build.make CMakeFiles/selene.dir/selene.c.s
.PHONY : selene.c.s

src/fs.o: src/fs.c.o
.PHONY : src/fs.o

# target to build an object file
src/fs.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/selene.dir/build.make CMakeFiles/selene.dir/src/fs.c.o
.PHONY : src/fs.c.o

src/fs.i: src/fs.c.i
.PHONY : src/fs.i

# target to preprocess a source file
src/fs.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/selene.dir/build.make CMakeFiles/selene.dir/src/fs.c.i
.PHONY : src/fs.c.i

src/fs.s: src/fs.c.s
.PHONY : src/fs.s

# target to generate assembly for a file
src/fs.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/selene.dir/build.make CMakeFiles/selene.dir/src/fs.c.s
.PHONY : src/fs.c.s

src/gl.o: src/gl.c.o
.PHONY : src/gl.o

# target to build an object file
src/gl.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/selene.dir/build.make CMakeFiles/selene.dir/src/gl.c.o
.PHONY : src/gl.c.o

src/gl.i: src/gl.c.i
.PHONY : src/gl.i

# target to preprocess a source file
src/gl.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/selene.dir/build.make CMakeFiles/selene.dir/src/gl.c.i
.PHONY : src/gl.c.i

src/gl.s: src/gl.c.s
.PHONY : src/gl.s

# target to generate assembly for a file
src/gl.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/selene.dir/build.make CMakeFiles/selene.dir/src/gl.c.s
.PHONY : src/gl.c.s

src/sdl2.o: src/sdl2.c.o
.PHONY : src/sdl2.o

# target to build an object file
src/sdl2.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/selene.dir/build.make CMakeFiles/selene.dir/src/sdl2.c.o
.PHONY : src/sdl2.c.o

src/sdl2.i: src/sdl2.c.i
.PHONY : src/sdl2.i

# target to preprocess a source file
src/sdl2.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/selene.dir/build.make CMakeFiles/selene.dir/src/sdl2.c.i
.PHONY : src/sdl2.c.i

src/sdl2.s: src/sdl2.c.s
.PHONY : src/sdl2.s

# target to generate assembly for a file
src/sdl2.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/selene.dir/build.make CMakeFiles/selene.dir/src/sdl2.c.s
.PHONY : src/sdl2.c.s

src/system.o: src/system.c.o
.PHONY : src/system.o

# target to build an object file
src/system.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/selene.dir/build.make CMakeFiles/selene.dir/src/system.c.o
.PHONY : src/system.c.o

src/system.i: src/system.c.i
.PHONY : src/system.i

# target to preprocess a source file
src/system.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/selene.dir/build.make CMakeFiles/selene.dir/src/system.c.i
.PHONY : src/system.c.i

src/system.s: src/system.c.s
.PHONY : src/system.s

# target to generate assembly for a file
src/system.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/selene.dir/build.make CMakeFiles/selene.dir/src/system.c.s
.PHONY : src/system.c.s

src/utils.o: src/utils.c.o
.PHONY : src/utils.o

# target to build an object file
src/utils.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/selene.dir/build.make CMakeFiles/selene.dir/src/utils.c.o
.PHONY : src/utils.c.o

src/utils.i: src/utils.c.i
.PHONY : src/utils.i

# target to preprocess a source file
src/utils.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/selene.dir/build.make CMakeFiles/selene.dir/src/utils.c.i
.PHONY : src/utils.c.i

src/utils.s: src/utils.c.s
.PHONY : src/utils.s

# target to generate assembly for a file
src/utils.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/selene.dir/build.make CMakeFiles/selene.dir/src/utils.c.s
.PHONY : src/utils.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... lua"
	@echo "... selene"
	@echo "... external/glad/src/glad.o"
	@echo "... external/glad/src/glad.i"
	@echo "... external/glad/src/glad.s"
	@echo "... external/lua/src/lapi.o"
	@echo "... external/lua/src/lapi.i"
	@echo "... external/lua/src/lapi.s"
	@echo "... external/lua/src/lauxlib.o"
	@echo "... external/lua/src/lauxlib.i"
	@echo "... external/lua/src/lauxlib.s"
	@echo "... external/lua/src/lbaselib.o"
	@echo "... external/lua/src/lbaselib.i"
	@echo "... external/lua/src/lbaselib.s"
	@echo "... external/lua/src/lcode.o"
	@echo "... external/lua/src/lcode.i"
	@echo "... external/lua/src/lcode.s"
	@echo "... external/lua/src/lcorolib.o"
	@echo "... external/lua/src/lcorolib.i"
	@echo "... external/lua/src/lcorolib.s"
	@echo "... external/lua/src/lctype.o"
	@echo "... external/lua/src/lctype.i"
	@echo "... external/lua/src/lctype.s"
	@echo "... external/lua/src/ldblib.o"
	@echo "... external/lua/src/ldblib.i"
	@echo "... external/lua/src/ldblib.s"
	@echo "... external/lua/src/ldebug.o"
	@echo "... external/lua/src/ldebug.i"
	@echo "... external/lua/src/ldebug.s"
	@echo "... external/lua/src/ldo.o"
	@echo "... external/lua/src/ldo.i"
	@echo "... external/lua/src/ldo.s"
	@echo "... external/lua/src/ldump.o"
	@echo "... external/lua/src/ldump.i"
	@echo "... external/lua/src/ldump.s"
	@echo "... external/lua/src/lfunc.o"
	@echo "... external/lua/src/lfunc.i"
	@echo "... external/lua/src/lfunc.s"
	@echo "... external/lua/src/lgc.o"
	@echo "... external/lua/src/lgc.i"
	@echo "... external/lua/src/lgc.s"
	@echo "... external/lua/src/linit.o"
	@echo "... external/lua/src/linit.i"
	@echo "... external/lua/src/linit.s"
	@echo "... external/lua/src/liolib.o"
	@echo "... external/lua/src/liolib.i"
	@echo "... external/lua/src/liolib.s"
	@echo "... external/lua/src/llex.o"
	@echo "... external/lua/src/llex.i"
	@echo "... external/lua/src/llex.s"
	@echo "... external/lua/src/lmathlib.o"
	@echo "... external/lua/src/lmathlib.i"
	@echo "... external/lua/src/lmathlib.s"
	@echo "... external/lua/src/lmem.o"
	@echo "... external/lua/src/lmem.i"
	@echo "... external/lua/src/lmem.s"
	@echo "... external/lua/src/loadlib.o"
	@echo "... external/lua/src/loadlib.i"
	@echo "... external/lua/src/loadlib.s"
	@echo "... external/lua/src/lobject.o"
	@echo "... external/lua/src/lobject.i"
	@echo "... external/lua/src/lobject.s"
	@echo "... external/lua/src/lopcodes.o"
	@echo "... external/lua/src/lopcodes.i"
	@echo "... external/lua/src/lopcodes.s"
	@echo "... external/lua/src/loslib.o"
	@echo "... external/lua/src/loslib.i"
	@echo "... external/lua/src/loslib.s"
	@echo "... external/lua/src/lparser.o"
	@echo "... external/lua/src/lparser.i"
	@echo "... external/lua/src/lparser.s"
	@echo "... external/lua/src/lstate.o"
	@echo "... external/lua/src/lstate.i"
	@echo "... external/lua/src/lstate.s"
	@echo "... external/lua/src/lstring.o"
	@echo "... external/lua/src/lstring.i"
	@echo "... external/lua/src/lstring.s"
	@echo "... external/lua/src/lstrlib.o"
	@echo "... external/lua/src/lstrlib.i"
	@echo "... external/lua/src/lstrlib.s"
	@echo "... external/lua/src/ltable.o"
	@echo "... external/lua/src/ltable.i"
	@echo "... external/lua/src/ltable.s"
	@echo "... external/lua/src/ltablib.o"
	@echo "... external/lua/src/ltablib.i"
	@echo "... external/lua/src/ltablib.s"
	@echo "... external/lua/src/ltm.o"
	@echo "... external/lua/src/ltm.i"
	@echo "... external/lua/src/ltm.s"
	@echo "... external/lua/src/lua.o"
	@echo "... external/lua/src/lua.i"
	@echo "... external/lua/src/lua.s"
	@echo "... external/lua/src/luac.o"
	@echo "... external/lua/src/luac.i"
	@echo "... external/lua/src/luac.s"
	@echo "... external/lua/src/lundump.o"
	@echo "... external/lua/src/lundump.i"
	@echo "... external/lua/src/lundump.s"
	@echo "... external/lua/src/lutf8lib.o"
	@echo "... external/lua/src/lutf8lib.i"
	@echo "... external/lua/src/lutf8lib.s"
	@echo "... external/lua/src/lvm.o"
	@echo "... external/lua/src/lvm.i"
	@echo "... external/lua/src/lvm.s"
	@echo "... external/lua/src/lzio.o"
	@echo "... external/lua/src/lzio.i"
	@echo "... external/lua/src/lzio.s"
	@echo "... selene.o"
	@echo "... selene.i"
	@echo "... selene.s"
	@echo "... src/fs.o"
	@echo "... src/fs.i"
	@echo "... src/fs.s"
	@echo "... src/gl.o"
	@echo "... src/gl.i"
	@echo "... src/gl.s"
	@echo "... src/sdl2.o"
	@echo "... src/sdl2.i"
	@echo "... src/sdl2.s"
	@echo "... src/system.o"
	@echo "... src/system.i"
	@echo "... src/system.s"
	@echo "... src/utils.o"
	@echo "... src/utils.i"
	@echo "... src/utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

