if ("$ENV{NDK_HOME}" STREQUAL "")
    message(FATAL_ERROR "NDK_HOME must be set")
endif ()
include("$ENV{NDK_HOME}/build/cmake/android.toolchain.cmake")
message("Android: ${ANDROID}")
if (${CMAKE_SYSTEM_PROCESSOR} STREQUAL "armv7-a")
set(triple "armv7-linux-android")
elseif (${CMAKE_SYSTEM_PROCESSOR} STREQUAL "x86_64")
set(triple "x86_64-linux-android")
endif()