local enums = {
    "INIT_EVERYTHING",
    "INIT_SENSOR",
    "INIT_AUDIO",
    "INIT_VIDEO",
    "INIT_JOYSTICK",
    "INIT_GAMECONTROLLER",
    "INIT_TIMER",
    "INIT_EVENTS",
    -- Audio
    "AUDIO_S16",
    "AUDIO_S16SYS",
    "AUDIO_F32",
    --* Application events *
    "QUIT",
    "APP_TERMINATING",
    "APP_LOWMEMORY",
    "APP_WILLENTERBACKGROUND",
    "APP_DIDENTERBACKGROUND",
    "APP_WILLENTERFOREGROUND",
    "APP_DIDENTERFOREGROUND",
    "LOCALECHANGED",

    -- Display events */
    "DISPLAYEVENT",

    -- Window events */
    "WINDOWEVENT",

    -- Keyboard events */
    "KEYDOWN",
    "KEYUP",
    "TEXTEDITING",
    "TEXTINPUT",
    "KEYMAPCHANGED",
    "TEXTEDITING_EXT",

    -- Mouse events */
    "MOUSEMOTION",
    "MOUSEBUTTONDOWN",
    "MOUSEBUTTONUP",
    "MOUSEWHEEL",

    -- Joystick events */
    "JOYAXISMOTION",
    "JOYBALLMOTION",
    "JOYHATMOTION",
    "JOYBUTTONDOWN",
    "JOYBUTTONUP",
    "JOYDEVICEADDED",
    "JOYDEVICEREMOVED",
    "JOYBATTERYUPDATED",

    -- Game controller events */
    "CONTROLLERAXISMOTION",
    "CONTROLLERBUTTONDOWN",
    "CONTROLLERBUTTONUP",
    "CONTROLLERDEVICEADDED",
    "CONTROLLERDEVICEREMOVED",
    "CONTROLLERDEVICEREMAPPED",
    "CONTROLLERTOUCHPADDOWN",
    "CONTROLLERTOUCHPADMOTION",
    "CONTROLLERTOUCHPADUP",
    "CONTROLLERSENSORUPDATE",

    -- Touch events */
    "FINGERDOWN",
    "FINGERUP",
    "FINGERMOTION",

    -- Gesture events */
    "DOLLARGESTURE",
    "DOLLARRECORD",
    "MULTIGESTURE",

    -- Clipboard events */
    "CLIPBOARDUPDATE",

    -- Drag and drop events */
    "DROPFILE",
    "DROPTEXT",
    "DROPBEGIN",
    "DROPCOMPLETE",

    -- Audio hotplug events */
    "AUDIODEVICEADDED",
    "AUDIODEVICEREMOVED",

    -- Sensor events */
    "SENSORUPDATE",

    -- Render events */
    "RENDER_TARGETS_RESET",
    "RENDER_DEVICE_RESET",

    -- Renderer
    "RENDERER_ACCELERATED",
    "RENDERER_TARGETTEXTURE",

    -- Window Events
    "WINDOWEVENT_CLOSE",
    "WINDOWEVENT_SIZE_CHANGED",
    "WINDOWEVENT_RESIZED",
    "WINDOWEVENT_MOVED",
    "WINDOWEVENT_MINIMIZED",
    "WINDOWEVENT_MAXIMIZED",
    "WINDOWEVENT_RESTORED",
    "WINDOWEVENT_SHOWN",
    "WINDOWEVENT_HIDDEN",
    "WINDOWEVENT_ENTER",
    "WINDOWEVENT_LEAVE",
    "WINDOWEVENT_FOCUS_GAINED",
    "WINDOWEVENT_FOCUS_LOST",
    "WINDOWEVENT_TAKE_FOCUS",
    "WINDOWEVENT_HIT_TEST",

    -- Window Flags
    "WINDOW_SHOWN",
    "WINDOW_OPENGL",
    "WINDOW_RESIZABLE",
    "WINDOW_FULLSCREEN",
    "WINDOW_FULLSCREEN_DESKTOP",
    "WINDOW_BORDERLESS",
    "WINDOW_ALWAYS_ON_TOP",

    "WINDOWPOS_CENTERED",
    -- Message Box
    "MESSAGEBOX_ERROR",
    "MESSAGEBOX_WARNING",
    "MESSAGEBOX_INFORMATION",
    -- GL
    "GL_DOUBLEBUFFER",
    "GL_DEPTH_SIZE",
    "GL_STENCIL_SIZE",
    "GL_CONTEXT_PROFILE_MASK",
    "GL_CONTEXT_MAJOR_VERSION",
    "GL_CONTEXT_MINOR_VERSION",
    "GL_CONTEXT_PROFILE_CORE",
    "GL_CONTEXT_PROFILE_COMPATIBILITY",
    "GL_CONTEXT_PROFILE_ES",
    -- TextureAccess
    "TEXTUREACCESS_STATIC",
    "TEXTUREACCESS_STREAMING",
    "TEXTUREACCESS_TARGET",

    -- PixelFormat
    "PIXELFORMAT_UNKNOWN",
    "PIXELFORMAT_RGB332",
    "PIXELFORMAT_RGB444",
    "PIXELFORMAT_RGB555",
    "PIXELFORMAT_BGR555",
    "PIXELFORMAT_ARGB4444",
    "PIXELFORMAT_RGBA4444",
    "PIXELFORMAT_ABGR4444",
    "PIXELFORMAT_BGRA4444",
    "PIXELFORMAT_RGB565",
    "PIXELFORMAT_BGR565",
    "PIXELFORMAT_RGB24",
    "PIXELFORMAT_BGR24",
    "PIXELFORMAT_RGB888",
    "PIXELFORMAT_BGR888",
    "PIXELFORMAT_ARGB8888",
    "PIXELFORMAT_RGBA8888",
    "PIXELFORMAT_ABGR8888",
    "PIXELFORMAT_BGRA8888",
    "PIXELFORMAT_RGBA32",
    "PIXELFORMAT_ARGB32",
    "PIXELFORMAT_BGRA32",
    "PIXELFORMAT_ABGR32",

    -- BlendMode
    "BLENDMODE_NONE",
    "BLENDMODE_BLEND",
    "BLENDMODE_ADD",
    "BLENDMODE_MOD",
    "BLENDMODE_MUL",
    "BLENDMODE_INVALID",

    -- RenderFlip
    "FLIP_NONE",
    "FLIP_VERTICAL",
    "FLIP_HORIZONTAL",

    -- ScaleMode
    "ScaleModeNearest",
    "ScaleModeLinear",
    "ScaleModeBest",
}
return enums