#ifndef SELENE_SDL_ENUMS_H_
#define SELENE_SDL_ENUMS_H_

BEGIN_ENUM(sdl_Enum)
// Init
  ENUM_FIELD(INIT_EVERYTHING, SDL_),
  ENUM_FIELD(INIT_SENSOR, SDL_),
  ENUM_FIELD(INIT_AUDIO, SDL_),
  ENUM_FIELD(INIT_VIDEO, SDL_),
  ENUM_FIELD(INIT_JOYSTICK, SDL_),
  ENUM_FIELD(INIT_GAMECONTROLLER, SDL_),
  ENUM_FIELD(INIT_TIMER, SDL_),
  ENUM_FIELD(INIT_EVENTS, SDL_),
  // Audio
  {"AUDIO_S16", AUDIO_S16},
  {"AUDIO_S16SYS", AUDIO_S16SYS},
  {"AUDIO_F32", AUDIO_F32},
  /* Application events */
  ENUM_FIELD(QUIT, SDL_),
  ENUM_FIELD(APP_TERMINATING, SDL_),
  ENUM_FIELD(APP_LOWMEMORY, SDL_),
  ENUM_FIELD(APP_WILLENTERBACKGROUND, SDL_),
  ENUM_FIELD(APP_DIDENTERBACKGROUND, SDL_),
  ENUM_FIELD(APP_WILLENTERFOREGROUND, SDL_),
  ENUM_FIELD(APP_DIDENTERFOREGROUND, SDL_),
  ENUM_FIELD(LOCALECHANGED, SDL_),

  /* Display events */
  ENUM_FIELD(DISPLAYEVENT, SDL_),

  /* Window events */
  ENUM_FIELD(WINDOWEVENT, SDL_),

    /* Keyboard events */
    ENUM_FIELD(KEYDOWN, SDL_),
    ENUM_FIELD(KEYUP, SDL_),
    ENUM_FIELD(TEXTEDITING, SDL_),
    ENUM_FIELD(TEXTINPUT, SDL_),
    ENUM_FIELD(KEYMAPCHANGED, SDL_),
    #if SDL_VERSION_ATLEAST(2, 0, 22)
    ENUM_FIELD(TEXTEDITING_EXT, SDL_),
    #endif

    /* Mouse events */
    ENUM_FIELD(MOUSEMOTION, SDL_),
    ENUM_FIELD(MOUSEBUTTONDOWN, SDL_),
    ENUM_FIELD(MOUSEBUTTONUP, SDL_),
    ENUM_FIELD(MOUSEWHEEL, SDL_),

    /* Joystick events */
    ENUM_FIELD(JOYAXISMOTION, SDL_),
    ENUM_FIELD(JOYBALLMOTION, SDL_),
    ENUM_FIELD(JOYHATMOTION, SDL_),
    ENUM_FIELD(JOYBUTTONDOWN, SDL_),
    ENUM_FIELD(JOYBUTTONUP, SDL_),
    ENUM_FIELD(JOYDEVICEADDED, SDL_),
    ENUM_FIELD(JOYDEVICEREMOVED, SDL_),
    #if SDL_VERSION_ATLEAST(2, 24, 0)
    ENUM_FIELD(JOYBATTERYUPDATED, SDL_),
    #endif

    /* Game controller events */
    ENUM_FIELD(CONTROLLERAXISMOTION, SDL_),
    ENUM_FIELD(CONTROLLERBUTTONDOWN, SDL_),
    ENUM_FIELD(CONTROLLERBUTTONUP, SDL_),
    ENUM_FIELD(CONTROLLERDEVICEADDED, SDL_),
    ENUM_FIELD(CONTROLLERDEVICEREMOVED, SDL_),
    ENUM_FIELD(CONTROLLERDEVICEREMAPPED, SDL_),
    ENUM_FIELD(CONTROLLERTOUCHPADDOWN, SDL_),
    ENUM_FIELD(CONTROLLERTOUCHPADMOTION, SDL_),
    ENUM_FIELD(CONTROLLERTOUCHPADUP, SDL_),
    ENUM_FIELD(CONTROLLERSENSORUPDATE, SDL_),

    /* Touch events */
    ENUM_FIELD(FINGERDOWN, SDL_),
    ENUM_FIELD(FINGERUP, SDL_),
    ENUM_FIELD(FINGERMOTION, SDL_),

    /* Gesture events */
    ENUM_FIELD(DOLLARGESTURE, SDL_),
    ENUM_FIELD(DOLLARRECORD, SDL_),
    ENUM_FIELD(MULTIGESTURE, SDL_),

    /* Clipboard events */
    ENUM_FIELD(CLIPBOARDUPDATE, SDL_),

    /* Drag and drop events */
    ENUM_FIELD(DROPFILE, SDL_),
    ENUM_FIELD(DROPTEXT, SDL_),
    ENUM_FIELD(DROPBEGIN, SDL_),
    ENUM_FIELD(DROPCOMPLETE, SDL_),

    /* Audio hotplug events */
    ENUM_FIELD(AUDIODEVICEADDED, SDL_),
    ENUM_FIELD(AUDIODEVICEREMOVED, SDL_),

    /* Sensor events */
    ENUM_FIELD(SENSORUPDATE, SDL_),

    /* Render events */
    ENUM_FIELD(RENDER_TARGETS_RESET, SDL_),
    ENUM_FIELD(RENDER_DEVICE_RESET, SDL_),

    // Renderer
    ENUM_FIELD(RENDERER_ACCELERATED, SDL_),
    ENUM_FIELD(RENDERER_TARGETTEXTURE, SDL_),

    // Window Events
    ENUM_FIELD(WINDOWEVENT_CLOSE, SDL_),
    ENUM_FIELD(WINDOWEVENT_SIZE_CHANGED, SDL_),
    ENUM_FIELD(WINDOWEVENT_RESIZED, SDL_), ENUM_FIELD(WINDOWEVENT_MOVED, SDL_),
    ENUM_FIELD(WINDOWEVENT_MINIMIZED, SDL_),
    ENUM_FIELD(WINDOWEVENT_MAXIMIZED, SDL_),
    ENUM_FIELD(WINDOWEVENT_RESTORED, SDL_), ENUM_FIELD(WINDOWEVENT_SHOWN, SDL_),
    ENUM_FIELD(WINDOWEVENT_HIDDEN, SDL_), ENUM_FIELD(WINDOWEVENT_ENTER, SDL_),
    ENUM_FIELD(WINDOWEVENT_LEAVE, SDL_),
    ENUM_FIELD(WINDOWEVENT_FOCUS_GAINED, SDL_),
    ENUM_FIELD(WINDOWEVENT_FOCUS_LOST, SDL_),
    ENUM_FIELD(WINDOWEVENT_TAKE_FOCUS, SDL_),
    ENUM_FIELD(WINDOWEVENT_HIT_TEST, SDL_),

    // Window Flags
    ENUM_FIELD(WINDOW_SHOWN, SDL_), ENUM_FIELD(WINDOW_OPENGL, SDL_),
    ENUM_FIELD(WINDOW_RESIZABLE, SDL_), ENUM_FIELD(WINDOW_FULLSCREEN, SDL_),
    ENUM_FIELD(WINDOW_FULLSCREEN_DESKTOP, SDL_),
    ENUM_FIELD(WINDOW_BORDERLESS, SDL_), ENUM_FIELD(WINDOW_ALWAYS_ON_TOP, SDL_),

    ENUM_FIELD(WINDOWPOS_CENTERED, SDL_),
    // Message Box
    ENUM_FIELD(MESSAGEBOX_ERROR, SDL_), ENUM_FIELD(MESSAGEBOX_WARNING, SDL_),
    ENUM_FIELD(MESSAGEBOX_INFORMATION, SDL_),
    // GL
    ENUM_FIELD(GL_DOUBLEBUFFER, SDL_), ENUM_FIELD(GL_DEPTH_SIZE, SDL_),
    ENUM_FIELD(GL_STENCIL_SIZE, SDL_),
    ENUM_FIELD(GL_CONTEXT_PROFILE_MASK, SDL_),
    ENUM_FIELD(GL_CONTEXT_MAJOR_VERSION, SDL_),
    ENUM_FIELD(GL_CONTEXT_MINOR_VERSION, SDL_),
    ENUM_FIELD(GL_CONTEXT_PROFILE_CORE, SDL_),
    ENUM_FIELD(GL_CONTEXT_PROFILE_COMPATIBILITY, SDL_),
    ENUM_FIELD(GL_CONTEXT_PROFILE_ES, SDL_),
    // TextureAccess
    ENUM_FIELD(TEXTUREACCESS_STATIC, SDL_),
    ENUM_FIELD(TEXTUREACCESS_STREAMING, SDL_),
    ENUM_FIELD(TEXTUREACCESS_TARGET, SDL_),

    // PixelFormat
    ENUM_FIELD(PIXELFORMAT_UNKNOWN, SDL_),
    ENUM_FIELD(PIXELFORMAT_RGB332, SDL_),
    ENUM_FIELD(PIXELFORMAT_RGB444, SDL_),
    ENUM_FIELD(PIXELFORMAT_RGB555, SDL_),
    ENUM_FIELD(PIXELFORMAT_BGR555, SDL_),
    ENUM_FIELD(PIXELFORMAT_ARGB4444, SDL_),
    ENUM_FIELD(PIXELFORMAT_RGBA4444, SDL_),
    ENUM_FIELD(PIXELFORMAT_ABGR4444, SDL_),
    ENUM_FIELD(PIXELFORMAT_BGRA4444, SDL_),
    ENUM_FIELD(PIXELFORMAT_RGB565, SDL_),
    ENUM_FIELD(PIXELFORMAT_BGR565, SDL_),
    ENUM_FIELD(PIXELFORMAT_RGB24, SDL_),
    ENUM_FIELD(PIXELFORMAT_BGR24, SDL_),
    ENUM_FIELD(PIXELFORMAT_RGB888, SDL_),
    ENUM_FIELD(PIXELFORMAT_BGR888, SDL_),
    ENUM_FIELD(PIXELFORMAT_ARGB8888, SDL_),
    ENUM_FIELD(PIXELFORMAT_RGBA8888, SDL_),
    ENUM_FIELD(PIXELFORMAT_ABGR8888, SDL_),
    ENUM_FIELD(PIXELFORMAT_BGRA8888, SDL_),
    ENUM_FIELD(PIXELFORMAT_RGBA32, SDL_),
    ENUM_FIELD(PIXELFORMAT_ARGB32, SDL_),
    ENUM_FIELD(PIXELFORMAT_BGRA32, SDL_),
    ENUM_FIELD(PIXELFORMAT_ABGR32, SDL_),

    // BlendMode
    ENUM_FIELD(BLENDMODE_NONE, SDL_),
    ENUM_FIELD(BLENDMODE_BLEND, SDL_),
    ENUM_FIELD(BLENDMODE_ADD, SDL_),
    ENUM_FIELD(BLENDMODE_MOD, SDL_),
    ENUM_FIELD(BLENDMODE_MUL, SDL_),
    ENUM_FIELD(BLENDMODE_INVALID, SDL_),

    // RenderFlip
    ENUM_FIELD(FLIP_NONE, SDL_),
    ENUM_FIELD(FLIP_VERTICAL, SDL_),
    ENUM_FIELD(FLIP_HORIZONTAL, SDL_),

    // ScaleMode
    ENUM_FIELD(ScaleModeNearest, SDL_),
    ENUM_FIELD(ScaleModeLinear, SDL_),
    ENUM_FIELD(ScaleModeBest, SDL_),
END_ENUM()

#endif /* SELENE_SDL_ENUMS_H_ */