message ("Check for correct system triple")

if (DEFINED triple)
    message("Has triple ${triple}")
else ()
    message("Has no triple")
    if (DEFINED MSVC)
        if (${CMAKE_SYSTEM_PROCESSOR} STREQUAL "x86")
            set(triple "x86-windows-msvc")
        else ()
            set(triple "x64-windows-msvc")
        endif ()
        message("MSVC Triple: ${triple}")
    elseif (DEFINED MINGW)
        if (${CMAKE_SYSTEM_PROCESSOR} STREQUAL "x86_64")
            set(triple "x86_64-w64-mingw32")
        elseif (${CMAKE_SYSTEM_PROCESSOR} STREQUAL "i686")
            set(triple "i686-w64-mingw32")
        endif ()
    elseif (DEFINED ANDROID)
        if ("${ANDROID_ABI}" STREQUAL "arm64-v8a")
            set(triple "aarch64-linux-android")
        elseif ("${ANDROID_ABI}" STREQUAL "armeabi-v7a")
            set(triple "armv7-linux-android")
        elseif ("${ANDROID_ABI}" STREQUAL "x86")
            set(triple "i386-linux-android")
        elseif ("${ANDROID_ABI}" STREQUAL "x86_64")
            set(triple "x86_64-linux-android")
        endif ()
    elseif (DEFINED EMSCRIPTEN)
        set(triple "wasm32-unknown-emscripten")
    elseif (DEFINED LINUX)
        if (${CMAKE_SYSTEM_PROCESSOR} STREQUAL "x86_64")
            set(triple "x86_64-linux-gnu")
        elseif (${CMAKE_SYSTEM_PROCESSOR} STREQUAL "i686")
            set(triple "i686-linux-gnu")
        elseif (${CMAKE_SYSTEM_PROCESSOR} STREQUAL "aarch64")
            set(triple "aarch64-linux-gnu")
        else ()
            set(triple "armv7-linux-gnu")
        endif ()
    endif ()
endif ()
message("TRIPLE: ${triple}")