set(SYSNAME "${CMAKE_SYSTEM_NAME}")

if ("${SYSNAME}" STREQUAL "Emscripten")
    set(EMSCRIPTEN 1)
    set(triple "wasm32-unknown-emscripten")
endif ()

if (WIN32 AND DEFINED CMAKE_GENERATOR_PLATFORM)
    message("GENERATOR: ${CMAKE_GENERATOR_PLATFORM}")
    if ("${CMAKE_GENERATOR_PLATFORM}" STREQUAL "")
        if ("${CMAKE_HOST_SYSTEM_PROCESSOR}" STREQUAL "AMD64")
            set(CMAKE_SYSTEM_PROCESSOR "x64")
        else ()
            set(CMAKE_SYSTEM_PROCESSOR "${CMAKE_HOST_SYSTEM_PROCESSOR}")
        endif ()
    elseif ("${CMAKE_GENERATOR_PLATFORM}" STREQUAL "Win32")
        set(CMAKE_SYSTEM_PROCESSOR "x86")
    else ()
        set(CMAKE_SYSTEM_PROCESSOR "${CMAKE_GENERATOR_PLATFORM}")
    endif()
elseif (NOT DEFINED MSVC)
    if(CMAKE_SCRIPT_MODE_FILE AND NOT CMAKE_PARENT_LIST_FILE)
        if (NOT CMAKE_BUILD_TYPE MATCHES Debug)
            add_definitions(-DNDEBUG)
        else ()
            add_definitions(-DDEBUG)
        endif ()
    endif ()
endif ()

message("-- Host System Name: ${CMAKE_HOST_SYSTEM_NAME}")
message("-- Host System Architecture: ${CMAKE_HOST_SYSTEM_PROCESSOR}")
message("-- Target System Name: ${CMAKE_SYSTEM_NAME}")
message("-- Target System Architecture: ${CMAKE_SYSTEM_PROCESSOR}")
message("-- Building for ${CMAKE_SYSTEM_NAME} ${CMAKE_SYSTEM_PROCESSOR} target")
message("-- WIN32: ${WIN32} | APPLE: ${APPLE} | UNIX: ${UNIX}")
message("--------------------------------------")
message("MSVC: ${MSVC}")
message("MINGW: ${MINGW}")
message("LINUX: ${LINUX}")
message("DARWIN: ${DARWIN}")
message("ANDROID: ${ANDROID}")
message("EMSCRIPTEN: ${EMSCRIPTEN}")
message("CMAKE_PREFIX_PATH: ${CMAKE_PREFIX_PATH}")
message("--------------------------------------")