name: Build Multiplatform
on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake libsdl2-dev

      - name: Build project
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_SYSTEM_PROCESSOR=x86_64 -DEXPORT_APPIMAGE=ON
          cmake --build build --target package --config Release

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-binaries
          path: build/

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install CMake
        run: |
          Invoke-WebRequest -Uri https://github.com/Kitware/CMake/releases/download/v3.26.4/cmake-3.26.4-windows-x86_64.msi -OutFile cmake.msi
          Start-Process msiexec -ArgumentList '/i cmake.msi /quiet /norestart' -Wait
          Remove-Item cmake.msi

      - name: Download SDL2
        run: |
          Invoke-WebRequest -Uri https://www.libsdl.org/release/SDL2-devel-2.30.11-VC.zip -OutFile SDL2.zip
          Expand-Archive -Path SDL2.zip -DestinationPath SDL2
          echo "SDL2_DIR=$env:GITHUB_WORKSPACE\SDL2\SDL2-2.30.11" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Build project
        run: |
          cmake -S . -B build -DSDL_PRECOMP_DIR=$env:SDL2_DIR -DCMAKE_BUILD_TYPE=Release
          cmake --build build --target package --config Release

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-binaries
          path: build/

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          brew install cmake sdl2

      - name: Build project
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build --target package --config Release

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-binaries
          path: build/

  build-android:
    runs-on: ubuntu-latest
    env:
      NDK_HOME: '${GITHUB_WORKSPACE}/.cache/AndroidSDK/ndk/25.2.9519653'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake libsdl2-dev
          sudo apt-get install openjdk-17-jre openjdk-17-jdk
          bash misc/scripts/download_sdl.sh source
          cmake -P cmake/scripts/SetupAndroidApk.cmake

      - name: Build project
        run: |
          cmake -DCMAKE_BUILD_TYPE=Release -P cmake/scripts/GenerateAndroidApk.cmake

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-binaries
          path: build/
  build-emscripten:
    runs-on: ubuntu-latest
    env:
      EMSDK_ROOT_DIR: '${GITHUB_WORKSPACE}/.cache/emsdk'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake git
          cmake -P cmake/scripts/SetupEmscripten.cmake

          echo "${EMSDK_ROOT_DIR}" >> $GITHUB_PATH

      - name: Build project
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=cmake/toolchains/Emscripten.cmake
          cmake --build build --target package --config Release
