name: Build Multiplatform
on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake libsdl2-dev

      - name: Build project
        run: |
          cmake -P cmake/scripts/DownloadAppImage.cmake
          cmake -S . -B build -DCPACK_PACKAGE_DIRECTORY=dist/ -DCMAKE_BUILD_TYPE=Release -DCMAKE_SYSTEM_PROCESSOR=x86_64 -DEXPORT_APPIMAGE=ON
          cmake --build build --target package --config Release

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-binaries
          path: |
            build/dist/*.tar.gz
            build/dist/*.AppImage

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install CMake
        run: |
          Invoke-WebRequest -Uri https://github.com/Kitware/CMake/releases/download/v3.26.4/cmake-3.26.4-windows-x86_64.msi -OutFile cmake.msi
          Start-Process msiexec -ArgumentList '/i cmake.msi /quiet /norestart' -Wait
          Remove-Item cmake.msi

      - name: Build project
        run: |
          cmake -P cmake/scripts/DownloadSDL2.cmake
          cmake -S . -B build -DCPACK_PACKAGE_DIRECTORY=dist/ -DCMAKE_BUILD_TYPE=Release
          cmake --build build --target package --config Release

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-binaries
          path: |
            build/dist/*.exe
            build/dist/*.zip

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          brew install cmake sdl2

      - name: Build project
        run: |
          mkdir dist/
          cmake -S . -B build -DCPACK_PACKAGE_DIRECTORY=dist/ -DCMAKE_BUILD_TYPE=Release
          cmake --build build --target package --config Release

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-binaries
          path: |
            build/dist/*.zip
            build/dist/*.dmg

  build-android:
    runs-on: ubuntu-latest
    env:
      NDK_HOME: '${GITHUB_WORKSPACE}/.cache/AndroidSDK/ndk/25.2.9519653'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake libsdl2-dev
          sudo apt-get install openjdk-17-jre openjdk-17-jdk

      - name: Build project
        run: |
          cmake -P cmake/scripts/DownloadSDL2.cmake
          cmake -P cmake/scripts/SetupAndroidSDK.cmake
          cmake -DCMAKE_BUILD_TYPE=Release -P cmake/scripts/GenerateAndroidApk.cmake

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-binaries
          path: build/android/app/build/outputs/apk/
  build-emscripten:
    runs-on: ubuntu-latest
    env:
      EMSDK_ROOT_DIR: '${GITHUB_WORKSPACE}/.cache/emsdk'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake git
          cmake -P cmake/scripts/SetupEmscripten.cmake

          echo "${EMSDK_ROOT_DIR}" >> $GITHUB_PATH

      - name: Build project
        run: |
          mkdir dist/
          cmake -B build -DCPACK_PACKAGE_DIRECTORY=dist/ -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=cmake/toolchains/Emscripten.cmake
          cmake --build build --target package --config Release

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: emscripten-binaries
          path: build/dist/*.zip